#!/bin/bash

CMD=/usr/bin/pkg-config
TEMPFILE=`mktemp /tmp/pkg-config-filter-XXXXXX`
# echo $TEMPFILE

if [ ! "$SYSROOT" ]; then
    echo "pkg-config-filter: missing \$SYSROOT environment variable"
    exit 2
fi

#if [ ! "$PKG_CONFIG_LIBDIR" ]; then
#    export PKG_CONFIG_LIBDIR=$SYSROOT/usr/pkgconfig/
#fi

export PKG_CONFIG_LIBDIR
export PKG_CONFIG_PATH

if $CMD "$@" > $TEMPFILE ; then
    cat $TEMPFILE |
    sed -e "s~\-L/*$SYSROOT/*~-L=/~g; s~\-I/*$SYSROOT/*~-I=/~g;" | # protect already given sysroot 
    sed -e "s~\-L/~-L=/~g; s~\-I/~-I=/~g;" | # add sysroot symbol to all absolute pathes
    sed -e "s~\-L\=~-L$SYSROOT~g; s~\-I\=~-I$SYSROOT~g;" # replace sysroot sign to sysroot path
    exit 0;
else
    echo "pkg-config failed!" >&2 
    cat $TEMPFILE
    exit 1
fi
